apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: default
data:
  init.sql: |
    CREATE TABLE messages (
        id SERIAL PRIMARY KEY,
        content TEXT NOT NULL
    );

    INSERT INTO messages (content) VALUES ('hello world');
