apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: brettenet/hello-k8-server:latest
        # image: hello-k8-server:latest
        # imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-username-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-password-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            value: mydatabase
          - name: POSTGRES_HOST
            value: postgres-service

---
apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
  selector:
    app: hello-server
